version: "3.8"

services:
  # Our NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./pulpo-backend
      # Only build development stage from Dockerfile
      target: development
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/thomas/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./pulpo-backend:/backend/src/app
      - /backend/src/app/node_modules/
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/pulpo
      DB_HOST: postgres
      DB_USER: user
      DB_PWD: password
      NODE_ENV: development
      JWT_SECRET: g3tpulp0
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
  
  # Our Angular Frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./pulpo-client
      target: development
    command: npm run start
    volumes:
      - ./pulpo-client:/frontend/src/app
      - /frontend/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - api

  # Our Postgres Database for NestJS to connect to
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pulpo
    ports:
      - 5432:5432

  # The Postgres Admin tool if we want to run some custom queries and so on against our Database
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

